version: "3.9"
services:
  local_shared:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    container_name: local-sharing
    command: '-p -u "workstation1;badpass123" -s "shared;/share" -n'
    volumes:
      - /mnt/shared:/share
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - 138:138/udp